spring:
  application:
    name: character-creator
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:chars
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
